export const cottonBall: any[] = [
    { id: 1, name: "baba1", email: "babaji1@gmail.com" },
    { id: 2, name: "baba2", email: "babaji2@gmail.com" },
    { id: 3, name: "baba3", email: "babaji3@gmail.com" },
    { id: 4, name: "baba4", email: "babaji4@gmail.com" },
    { id: 5, name: "baba5", email: "babaji5@gmail.com" },
    { id: 6, name: "baba6", email: "babaji6@gmail.com" },
    { id: 7, name: "baba7", email: "babaji7@gmail.com" },
    { id: 8, name: "baba8", email: "babaji8@gmail.com" },
    { id: 9, name: "baba9", email: "babaji9@gmail.com" },
    { id: 10, name: "baba10", email: "babaji10@gmail.com" },
    { id: 11, name: "baba11", email: "babaji11@gmail.com" },
    { id: 12, name: "baba12", email: "babaji12@gmail.com" },
    { id: 13, name: "baba13", email: "babaji13@gmail.com" },
    { id: 14, name: "baba14", email: "babaji14@gmail.com" },
    { id: 15, name: "baba15", email: "babaji15@gmail.com" },
    { id: 16, name: "baba16", email: "babaji16@gmail.com" },
    { id: 17, name: "baba17", email: "babaji17@gmail.com" },
    { id: 18, name: "baba18", email: "babaji18@gmail.com" },
    { id: 19, name: "baba19", email: "babaji19@gmail.com" },
    { id: 20, name: "baba20", email: "babaji20@gmail.com" },
    { id: 21, name: "baba21", email: "babaji21@gmail.com" },
    { id: 22, name: "baba22", email: "babaji22@gmail.com" },
    { id: 23, name: "baba23", email: "babaji23@gmail.com" },
    { id: 24, name: "baba24", email: "babaji24@gmail.com" },
    { id: 25, name: "baba25", email: "babaji25@gmail.com" },
    { id: 26, name: "baba26", email: "babaji26@gmail.com" },
    { id: 27, name: "baba27", email: "babaji27@gmail.com" }
]


export const countries: any[] = [
    {
        id: 1, code: "IN", name: "India", state: [
            { id: 1, code: "AAN", name: "Andaman and Nicobar" },
            { id: 2, code: "AP", name: "Andhra Pradesh" },
            { id: 3, code: "ANP", name: "Arunachal Pradesh" },
            { id: 4, code: "ASM", name: "Assam" },
            { id: 5, code: "BR", name: "Bihar" },
            { id: 7, code: "CH", name: "Chhattisgarh" },
            { id: 8, code: "DB", name: "Dadra and Nagar Haveli" },
            { id: 9, code: "DD", name: "Daman and Diu" },
            { id: 10, code: "DL", name: "Delhi" },
            { id: 11, code: "GA", name: "Goa" },
            { id: 12, code: "GU", name: "Gujarat" },
            { id: 13, code: "HR", name: "Haryana" },
            { id: 14, code: "HP", name: "Himachal Pradesh" },
            { id: 15, code: "JK", name: "Jammu and Kashmir" },
            { id: 16, code: "JH", name: "Jharkhand" },
            { id: 17, code: "KA", name: "Karnataka" },
            { id: 18, code: "KL", name: "Kerala" },
            { id: 19, code: "LP", name: "Lakshadweep" },
            { id: 20, code: "MP", name: "Madhya Pradesh" },
            { id: 21, code: "MH", name: "Maharashtra" },
            { id: 22, code: "MP", name: "Manipur" },
            { id: 23, code: "MG", name: "Meghalaya" },
            { id: 24, code: "MZ", name: "Mizoram" },
            { id: 25, code: "NG", name: "Nagaland" },
            { id: 26, code: "OR", name: "Orissa" },
            { id: 27, code: "PU", name: "Puducherry" },
            { id: 28, code: "PN", name: "Punjab" },
            { id: 29, code: "RJ", name: "Rajasthan" },
            { id: 30, code: "SK", name: "Sikkim" },
            { id: 31, code: "TN", name: "Tamil Nadu" },
            { id: 32, code: "TL", name: "Telangana" },
            { id: 33, code: "TR", name: "Tripura" },
            { id: 34, code: "UP", name: "Uttar Pradesh" },
            { id: 35, code: "UK", name: "Uttarakhand" },
            { id: 36, code: "WB", name: "West Bengal" },
        ]
    },
    {
        id: 2, code: "SG", name: "Singapore", state: [
            { id: 1, code: "SGS", name: "Singapore State" }
        ]
    },
    {
        id: 3, code: "US", name: "United States", state: [
            { id: 1, name: "Alabama", code: "AL" },
            { id: 2, name: "Alaska", code: "AK" },
            { id: 3, name: "Arizona", code: "AZ" },
            { id: 4, name: "Arkansas", code: "AR" },
            { id: 5, name: "California", code: "CA" },
            { id: 6, name: "Colorado", code: "CO" },
            { id: 7, name: "Connecticut", code: "CT" },
            { id: 8, name: "Delaware", code: "DE" },
            { id: 9, name: "Florida", code: "FL" },
            { id: 10, name: "Georgia", code: "GA" },
            { id: 11, name: "Hawaii", code: "HI" },
            { id: 12, name: "Idaho", code: "ID" },
            { id: 13, name: "Illinois", code: "IL" },
            { id: 14, name: "Indiana", code: "IN" },
            { id: 15, name: "Iowa", code: "IA" },
            { id: 16, name: "Kansas", code: "KS" },
            { id: 17, name: "Kentucky[D]", code: "KY" },
            { id: 18, name: "Louisiana", code: "LA" },
            { id: 19, name: "Maine", code: "ME" },
            { id: 20, name: "Maryland", code: "MD" },
            { id: 21, name: "Massachusetts[D]", code: "MA" },
            { id: 22, name: "Michigan", code: "MI" },
            { id: 23, name: "Minnesota", code: "MN" },
            { id: 24, name: "Mississippi", code: "MS" },
            { id: 25, name: "Missouri", code: "MO" },
            { id: 26, name: "Montana", code: "MT" },
            { id: 27, name: "Nebraska", code: "NE" },
            { id: 28, name: "Nevada", code: "NV" },
            { id: 29, name: "New Hampshire", code: "NH" },
            { id: 30, name: "New Jersey", code: "NJ" },
            { id: 31, name: "New Mexico", code: "NM" },
            { id: 32, name: "New York", code: "NY" },
            { id: 33, name: "North Carolina", code: "NC" },
            { id: 34, name: "North Dakota", code: "ND" },
            { id: 35, name: "Ohio", code: "OH" },
            { id: 36, name: "Oklahoma", code: "OK" },
            { id: 37, name: "Oregon", code: "OR" },
            { id: 38, name: "Pennsylvania[D]", code: "PA" },
            { id: 39, name: "Rhode Island", code: "RI" },
            { id: 40, name: "South Carolina", code: "SC" },
            { id: 41, name: "South Dakota", code: "SD" },
            { id: 42, name: "Tennessee", code: "TN" },
            { id: 43, name: "Texas", code: "TX" },
            { id: 44, name: "Utah", code: "UT" },
            { id: 45, name: "Vermont", code: "VT" },
            { id: 46, name: "Virginia[D]", code: "VA" },
            { id: 47, name: "Washington", code: "WA" },
            { id: 48, name: "West Virginia", code: "WV" },
            { id: 49, name: "Wisconsin", code: "WI" },
            { id: 50, name: "Wyoming", code: "WY" },
        ]
    },
    {
        id: 4, code: "AU", name: "Australia", state: [
            { id: 1, name: "New South Wales", code: "NSW" },
            { id: 2, name: "Queensland", code: "QLD" },
            { id: 3, name: "South Australia", code: "SA" },
            { id: 4, name: "Tasmania", code: "TAS" },
            { id: 5, name: "Victoria", code: "VIC" },
            { id: 6, name: "Western Australia", code: "WA" }]
    },
]


// { id: 28, name: "baba28", email: "babaji28@gmail.com" },
//     { id: 29, name: "baba29", email: "babaji29@gmail.com" },
//     { id: 30, name: "baba30", email: "babaji30@gmail.com" },
//     { id: 31, name: "baba31", email: "babaji31@gmail.com" },
//     { id: 32, name: "baba32", email: "babaji32@gmail.com" },
//     { id: 33, name: "baba33", email: "babaji33@gmail.com" },
//     { id: 34, name: "baba34", email: "babaji34@gmail.com" },
//     { id: 35, name: "baba35", email: "babaji35@gmail.com" },
//     { id: 36, name: "baba36", email: "babaji36@gmail.com" },
//     { id: 37, name: "baba37", email: "babaji37@gmail.com" },
//     { id: 38, name: "baba38", email: "babaji38@gmail.com" },
//     { id: 39, name: "baba39", email: "babaji39@gmail.com" },
//     { id: 40, name: "baba40", email: "babaji40@gmail.com" },
//     { id: 41, name: "baba41", email: "babaji41@gmail.com" },
//     { id: 42, name: "baba42", email: "babaji42@gmail.com" },
//     { id: 43, name: "baba43", email: "babaji43@gmail.com" },
//     { id: 44, name: "baba44", email: "babaji44@gmail.com" },
//     { id: 45, name: "baba45", email: "babaji45@gmail.com" },
//     { id: 46, name: "baba46", email: "babaji46@gmail.com" },
//     { id: 47, name: "baba47", email: "babaji47@gmail.com" },
//     { id: 48, name: "baba48", email: "babaji48@gmail.com" },
//     { id: 49, name: "baba49", email: "babaji49@gmail.com" },
//     { id: 50, name: "baba50", email: "babaji50@gmail.com" },
//     { id: 51, name: "baba51", email: "babaji51@gmail.com" },
//     { id: 52, name: "baba52", email: "babaji52@gmail.com" },
//     { id: 53, name: "baba53", email: "babaji53@gmail.com" },
//     { id: 54, name: "baba54", email: "babaji54@gmail.com" },
//     { id: 55, name: "baba55", email: "babaji55@gmail.com" },
//     { id: 56, name: "baba56", email: "babaji56@gmail.com" },
//     { id: 57, name: "baba57", email: "babaji57@gmail.com" },
//     { id: 58, name: "baba58", email: "babaji58@gmail.com" },
//     { id: 59, name: "baba59", email: "babaji59@gmail.com" },
//     { id: 60, name: "baba60", email: "babaji60@gmail.com" },
//     { id: 61, name: "baba61", email: "babaji61@gmail.com" },
//     { id: 62, name: "baba62", email: "babaji62@gmail.com" },
//     { id: 63, name: "baba63", email: "babaji63@gmail.com" },
//     { id: 64, name: "baba64", email: "babaji64@gmail.com" },
//     { id: 65, name: "baba65", email: "babaji65@gmail.com" },
//     { id: 66, name: "baba66", email: "babaji66@gmail.com" },
//     { id: 67, name: "baba67", email: "babaji67@gmail.com" },
//     { id: 68, name: "baba68", email: "babaji68@gmail.com" },
//     { id: 69, name: "baba69", email: "babaji69@gmail.com" },
//     { id: 70, name: "baba70", email: "babaji70@gmail.com" },
//     { id: 71, name: "baba71", email: "babaji71@gmail.com" },
//     { id: 72, name: "baba72", email: "babaji72@gmail.com" },
//     { id: 73, name: "baba73", email: "babaji73@gmail.com" },
//     { id: 74, name: "baba74", email: "babaji74@gmail.com" },
//     { id: 75, name: "baba75", email: "babaji75@gmail.com" },
//     { id: 76, name: "baba76", email: "babaji76@gmail.com" },
//     { id: 77, name: "baba77", email: "babaji77@gmail.com" },
//     { id: 78, name: "baba78", email: "babaji78@gmail.com" },
//     { id: 79, name: "baba79", email: "babaji79@gmail.com" },
//     { id: 80, name: "baba80", email: "babaji80@gmail.com" },
//     { id: 81, name: "baba81", email: "babaji81@gmail.com" },
//     { id: 82, name: "baba82", email: "babaji82@gmail.com" },
//     { id: 83, name: "baba83", email: "babaji83@gmail.com" },
//     { id: 84, name: "baba84", email: "babaji84@gmail.com" },
//     { id: 85, name: "baba85", email: "babaji85@gmail.com" },
//     { id: 86, name: "baba86", email: "babaji86@gmail.com" },
//     { id: 87, name: "baba87", email: "babaji87@gmail.com" },
//     { id: 88, name: "baba88", email: "babaji88@gmail.com" },
//     { id: 89, name: "baba89", email: "babaji89@gmail.com" },
//     { id: 90, name: "baba90", email: "babaji90@gmail.com" },
//     { id: 91, name: "baba91", email: "babaji91@gmail.com" },
//     { id: 92, name: "baba92", email: "babaji92@gmail.com" },
//     { id: 93, name: "baba93", email: "babaji93@gmail.com" },
//     { id: 94, name: "baba94", email: "babaji94@gmail.com" },
//     { id: 95, name: "baba95", email: "babaji95@gmail.com" },
//     { id: 96, name: "baba96", email: "babaji96@gmail.com" },
//     { id: 97, name: "baba97", email: "babaji97@gmail.com" },
//     { id: 98, name: "baba98", email: "babaji98@gmail.com" },
//     { id: 99, name: "baba99", email: "babaji99@gmail.com" },
//     { id: 100, name: "baba100", email: "babaji100@gmail.com" },
//     { id: 101, name: "baba101", email: "babaji101@gmail.com" },
//     { id: 102, name: "baba102", email: "babaji102@gmail.com" },
//     { id: 103, name: "baba103", email: "babaji103@gmail.com" },
//     { id: 104, name: "baba104", email: "babaji104@gmail.com" },
//     { id: 105, name: "baba105", email: "babaji105@gmail.com" },
//     { id: 106, name: "baba106", email: "babaji106@gmail.com" },
//     { id: 107, name: "baba107", email: "babaji107@gmail.com" },
//     { id: 108, name: "baba108", email: "babaji108@gmail.com" },
//     { id: 109, name: "baba109", email: "babaji109@gmail.com" },
//     { id: 110, name: "baba110", email: "babaji110@gmail.com" },
//     { id: 111, name: "baba111", email: "babaji111@gmail.com" },
//     { id: 112, name: "baba112", email: "babaji112@gmail.com" },
//     { id: 113, name: "baba113", email: "babaji113@gmail.com" },
//     { id: 114, name: "baba114", email: "babaji114@gmail.com" },
//     { id: 115, name: "baba115", email: "babaji115@gmail.com" },
//     { id: 116, name: "baba116", email: "babaji116@gmail.com" },
//     { id: 117, name: "baba117", email: "babaji117@gmail.com" },
//     { id: 118, name: "baba118", email: "babaji118@gmail.com" },
//     { id: 119, name: "baba119", email: "babaji119@gmail.com" },
//     { id: 120, name: "baba120", email: "babaji120@gmail.com" },
//     { id: 121, name: "baba121", email: "babaji121@gmail.com" },
//     { id: 122, name: "baba122", email: "babaji122@gmail.com" },
//     { id: 123, name: "baba123", email: "babaji123@gmail.com" },
//     { id: 124, name: "baba124", email: "babaji124@gmail.com" },
//     { id: 125, name: "baba125", email: "babaji125@gmail.com" },
//     { id: 126, name: "baba126", email: "babaji126@gmail.com" },
//     { id: 127, name: "baba127", email: "babaji127@gmail.com" },
//     { id: 128, name: "baba128", email: "babaji128@gmail.com" },
//     { id: 129, name: "baba129", email: "babaji129@gmail.com" },
//     { id: 130, name: "baba130", email: "babaji130@gmail.com" },
//     { id: 131, name: "baba131", email: "babaji131@gmail.com" },
//     { id: 132, name: "baba132", email: "babaji132@gmail.com" },
//     { id: 133, name: "baba133", email: "babaji133@gmail.com" },
//     { id: 134, name: "baba134", email: "babaji134@gmail.com" },
//     { id: 135, name: "baba135", email: "babaji135@gmail.com" },
//     { id: 136, name: "baba136", email: "babaji136@gmail.com" },
//     { id: 137, name: "baba137", email: "babaji137@gmail.com" },
//     { id: 138, name: "baba138", email: "babaji138@gmail.com" },
//     { id: 139, name: "baba139", email: "babaji139@gmail.com" },
//     { id: 140, name: "baba140", email: "babaji140@gmail.com" },
//     { id: 141, name: "baba141", email: "babaji141@gmail.com" },
//     { id: 142, name: "baba142", email: "babaji142@gmail.com" },
//     { id: 143, name: "baba143", email: "babaji143@gmail.com" },
//     { id: 144, name: "baba144", email: "babaji144@gmail.com" },
//     { id: 145, name: "baba145", email: "babaji145@gmail.com" },
//     { id: 146, name: "baba146", email: "babaji146@gmail.com" },
//     { id: 147, name: "baba147", email: "babaji147@gmail.com" },
//     { id: 148, name: "baba148", email: "babaji148@gmail.com" },
//     { id: 149, name: "baba149", email: "babaji149@gmail.com" },
//     { id: 150, name: "baba150", email: "babaji150@gmail.com" },
//     { id: 151, name: "baba151", email: "babaji151@gmail.com" },
//     { id: 152, name: "baba152", email: "babaji152@gmail.com" },
//     { id: 153, name: "baba153", email: "babaji153@gmail.com" },
//     { id: 154, name: "baba154", email: "babaji154@gmail.com" },
//     { id: 155, name: "baba155", email: "babaji155@gmail.com" },
//     { id: 156, name: "baba156", email: "babaji156@gmail.com" },
//     { id: 157, name: "baba157", email: "babaji157@gmail.com" },
//     { id: 158, name: "baba158", email: "babaji158@gmail.com" },
//     { id: 159, name: "baba159", email: "babaji159@gmail.com" },
//     { id: 160, name: "baba160", email: "babaji160@gmail.com" },
//     { id: 161, name: "baba161", email: "babaji161@gmail.com" },
//     { id: 162, name: "baba162", email: "babaji162@gmail.com" },
//     { id: 163, name: "baba163", email: "babaji163@gmail.com" },
//     { id: 164, name: "baba164", email: "babaji164@gmail.com" },
//     { id: 165, name: "baba165", email: "babaji165@gmail.com" },
//     { id: 166, name: "baba166", email: "babaji166@gmail.com" },
//     { id: 167, name: "baba167", email: "babaji167@gmail.com" },
//     { id: 168, name: "baba168", email: "babaji168@gmail.com" },
//     { id: 169, name: "baba169", email: "babaji169@gmail.com" },
//     { id: 170, name: "baba170", email: "babaji170@gmail.com" },
//     { id: 171, name: "baba171", email: "babaji171@gmail.com" },
//     { id: 172, name: "baba172", email: "babaji172@gmail.com" },
//     { id: 173, name: "baba173", email: "babaji173@gmail.com" },
//     { id: 174, name: "baba174", email: "babaji174@gmail.com" },
//     { id: 175, name: "baba175", email: "babaji175@gmail.com" },
//     { id: 176, name: "baba176", email: "babaji176@gmail.com" },
//     { id: 177, name: "baba177", email: "babaji177@gmail.com" },
//     { id: 178, name: "baba178", email: "babaji178@gmail.com" },
//     { id: 179, name: "baba179", email: "babaji179@gmail.com" },
//     { id: 180, name: "baba180", email: "babaji180@gmail.com" },
//     { id: 181, name: "baba181", email: "babaji181@gmail.com" },
//     { id: 182, name: "baba182", email: "babaji182@gmail.com" },
//     { id: 183, name: "baba183", email: "babaji183@gmail.com" },
//     { id: 184, name: "baba184", email: "babaji184@gmail.com" },
//     { id: 185, name: "baba185", email: "babaji185@gmail.com" },
//     { id: 186, name: "baba186", email: "babaji186@gmail.com" },
//     { id: 187, name: "baba187", email: "babaji187@gmail.com" },
//     { id: 188, name: "baba188", email: "babaji188@gmail.com" },
//     { id: 189, name: "baba189", email: "babaji189@gmail.com" },
//     { id: 190, name: "baba190", email: "babaji190@gmail.com" },
//     { id: 191, name: "baba191", email: "babaji191@gmail.com" },
//     { id: 192, name: "baba192", email: "babaji192@gmail.com" },
//     { id: 193, name: "baba193", email: "babaji193@gmail.com" },
//     { id: 194, name: "baba194", email: "babaji194@gmail.com" },
//     { id: 195, name: "baba195", email: "babaji195@gmail.com" },
//     { id: 196, name: "baba196", email: "babaji196@gmail.com" },
//     { id: 197, name: "baba197", email: "babaji197@gmail.com" },
//     { id: 198, name: "baba198", email: "babaji198@gmail.com" },
//     { id: 199, name: "baba199", email: "babaji199@gmail.com" },
//     { id: 200, name: "baba200", email: "babaji200@gmail.com" },
//     { id: 201, name: "baba201", email: "babaji201@gmail.com" },
//     { id: 202, name: "baba202", email: "babaji202@gmail.com" },
//     { id: 203, name: "baba203", email: "babaji203@gmail.com" },
//     { id: 204, name: "baba204", email: "babaji204@gmail.com" },
//     { id: 205, name: "baba205", email: "babaji205@gmail.com" },
//     { id: 206, name: "baba206", email: "babaji206@gmail.com" },
//     { id: 207, name: "baba207", email: "babaji207@gmail.com" },
//     { id: 208, name: "baba208", email: "babaji208@gmail.com" },


export const funds: any[] = [
    { 
      id: 1, 
      title: "milaap", 
      description: "It was on the third of November 2018 that we were taken to Karunashraya by our school as a project of the Rotary Club of Bangalore. The instant we saw the miserable state of the cancer patients, something prodigious stirred inside us. The bleak reality was that the patients were under an awful amount of suffering ...", 
      imageUrl: "https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1602914530/production/images/campaign/220990/karun_2_zd8inl_1602914533.jpg", 
      link: "https://milaap.org/fundraisers/support-cancer-patient-2" 
    },
    { 
      id: 2, 
      title: "milaap", 
      description: "For most people, it would have been a time to prepare for a comfortable retired life. But Kishore Rao, who had been serving at a corporate for 28 years, had an inner calling and took early retirement at 55 to help those who were suffering from cancer. Hailing from Bengaluru, he is now 81 and runs Karunashraya, a free facility for end-stage cancer patients. ...", 
      imageUrl: "https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1540058388/production/images/campaign/27185/Cover_Image_ycpkdb_1540058390.jpg", 
      link: "https://milaap.org/fundraisers/helping-cancer-patients" 
    },
    { 
      id: 3, 
      title: "milaap", 
      description: "I am Kumar Kuppuswamy, a passionate Ultra runner, have been running Marathons, Ultra Marathons for over 11 years now, for wellness and recreation. Also, I have always wished to use running to raise funds for a good cause and hope to achieve it with your great support. ...", 
      imageUrl: "https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1534488949/production/images/campaign/44957/Img-3_1507022087_ouyvih_1534488951.jpg", 
      link: "https://milaap.org/fundraisers/help-karunashraya" 
    },
    { 
      id: 4, 
      title: "giveindia.org", 
      description: "Studies show over 70% of senior citizens in India face abuse - verbal, physical, emotional and financial. They also live with deteriorating health conditions they cannot afford to treat. Mission: #EldersLivesMatter ensures they are not alone, sick and hungry ...", 
      imageUrl: "https://cdn.givind.org/static/images/campaign/EldersLivesMatter-cta-image.jpg", 
      link: "https://www.giveindia.org/missions/mission-elders-lives-matter" 
    },
    { 
      id: 5, 
      title: "giveindia.org", 
      description: "One in three of the world's malnourished children lives in India. Our children are going to school hungry. They suffer from lack of concentration and reduced cognitive development, directly leading to their dropping out of school. Join us in our mission to prevent hunger diminishing our children’s opportunities to succeed. ...", 
      imageUrl: "https://cdn.givind.org/static/images/campaign/target-image1.jpg", 
      link: "https://www.giveindia.org/campaign/mission-10-million-meals" 
    }
  ];