export const countries: any[] = [
    {
        id: 1, code: "IN", name: "India", state: [
            { id: 1, code: "AAN", name: "Andaman and Nicobar" },
            { id: 2, code: "AP", name: "Andhra Pradesh" },
            { id: 3, code: "ANP", name: "Arunachal Pradesh" },
            { id: 4, code: "ASM", name: "Assam" },
            { id: 5, code: "BR", name: "Bihar" },
            { id: 7, code: "CH", name: "Chhattisgarh" },
            { id: 8, code: "DB", name: "Dadra and Nagar Haveli" },
            { id: 9, code: "DD", name: "Daman and Diu" },
            { id: 10, code: "DL", name: "Delhi" },
            { id: 11, code: "GA", name: "Goa" },
            { id: 12, code: "GU", name: "Gujarat" },
            { id: 13, code: "HR", name: "Haryana" },
            { id: 14, code: "HP", name: "Himachal Pradesh" },
            { id: 15, code: "JK", name: "Jammu and Kashmir" },
            { id: 16, code: "JH", name: "Jharkhand" },
            { id: 17, code: "KA", name: "Karnataka" },
            { id: 18, code: "KL", name: "Kerala" },
            { id: 19, code: "LP", name: "Lakshadweep" },
            { id: 20, code: "MP", name: "Madhya Pradesh" },
            { id: 21, code: "MH", name: "Maharashtra" },
            { id: 22, code: "MP", name: "Manipur" },
            { id: 23, code: "MG", name: "Meghalaya" },
            { id: 24, code: "MZ", name: "Mizoram" },
            { id: 25, code: "NG", name: "Nagaland" },
            { id: 26, code: "OR", name: "Orissa" },
            { id: 27, code: "PU", name: "Puducherry" },
            { id: 28, code: "PN", name: "Punjab" },
            { id: 29, code: "RJ", name: "Rajasthan" },
            { id: 30, code: "SK", name: "Sikkim" },
            { id: 31, code: "TN", name: "Tamil Nadu" },
            { id: 32, code: "TL", name: "Telangana" },
            { id: 33, code: "TR", name: "Tripura" },
            { id: 34, code: "UP", name: "Uttar Pradesh" },
            { id: 35, code: "UK", name: "Uttarakhand" },
            { id: 36, code: "WB", name: "West Bengal" },
        ]
    },
    {
        id: 2, code: "SG", name: "Singapore", state: [
            { id: 1, code: "SGS", name: "Singapore State" }
        ]
    },
    {
        id: 3, code: "US", name: "United States", state: [
            { id: 1, name: "Alabama", code: "AL" },
            { id: 2, name: "Alaska", code: "AK" },
            { id: 3, name: "Arizona", code: "AZ" },
            { id: 4, name: "Arkansas", code: "AR" },
            { id: 5, name: "California", code: "CA" },
            { id: 6, name: "Colorado", code: "CO" },
            { id: 7, name: "Connecticut", code: "CT" },
            { id: 8, name: "Delaware", code: "DE" },
            { id: 9, name: "Florida", code: "FL" },
            { id: 10, name: "Georgia", code: "GA" },
            { id: 11, name: "Hawaii", code: "HI" },
            { id: 12, name: "Idaho", code: "ID" },
            { id: 13, name: "Illinois", code: "IL" },
            { id: 14, name: "Indiana", code: "IN" },
            { id: 15, name: "Iowa", code: "IA" },
            { id: 16, name: "Kansas", code: "KS" },
            { id: 17, name: "Kentucky[D]", code: "KY" },
            { id: 18, name: "Louisiana", code: "LA" },
            { id: 19, name: "Maine", code: "ME" },
            { id: 20, name: "Maryland", code: "MD" },
            { id: 21, name: "Massachusetts[D]", code: "MA" },
            { id: 22, name: "Michigan", code: "MI" },
            { id: 23, name: "Minnesota", code: "MN" },
            { id: 24, name: "Mississippi", code: "MS" },
            { id: 25, name: "Missouri", code: "MO" },
            { id: 26, name: "Montana", code: "MT" },
            { id: 27, name: "Nebraska", code: "NE" },
            { id: 28, name: "Nevada", code: "NV" },
            { id: 29, name: "New Hampshire", code: "NH" },
            { id: 30, name: "New Jersey", code: "NJ" },
            { id: 31, name: "New Mexico", code: "NM" },
            { id: 32, name: "New York", code: "NY" },
            { id: 33, name: "North Carolina", code: "NC" },
            { id: 34, name: "North Dakota", code: "ND" },
            { id: 35, name: "Ohio", code: "OH" },
            { id: 36, name: "Oklahoma", code: "OK" },
            { id: 37, name: "Oregon", code: "OR" },
            { id: 38, name: "Pennsylvania[D]", code: "PA" },
            { id: 39, name: "Rhode Island", code: "RI" },
            { id: 40, name: "South Carolina", code: "SC" },
            { id: 41, name: "South Dakota", code: "SD" },
            { id: 42, name: "Tennessee", code: "TN" },
            { id: 43, name: "Texas", code: "TX" },
            { id: 44, name: "Utah", code: "UT" },
            { id: 45, name: "Vermont", code: "VT" },
            { id: 46, name: "Virginia[D]", code: "VA" },
            { id: 47, name: "Washington", code: "WA" },
            { id: 48, name: "West Virginia", code: "WV" },
            { id: 49, name: "Wisconsin", code: "WI" },
            { id: 50, name: "Wyoming", code: "WY" },
        ]
    },
    {
        id: 4, code: "AU", name: "Australia", state: [
            { id: 1, name: "New South Wales", code: "NSW" },
            { id: 2, name: "Queensland", code: "QLD" },
            { id: 3, name: "South Australia", code: "SA" },
            { id: 4, name: "Tasmania", code: "TAS" },
            { id: 5, name: "Victoria", code: "VIC" },
            { id: 6, name: "Western Australia", code: "WA" }]
    },
]